config/routes.rb
Sapm::Application.routes.draw do

  devise_for :users, controllers: { confirmations: "confirmations" }
  as :user do
    put '/users/confirmation' => 'confirmations#update', as: :update_user_confirmation
  end

  namespace :admin do
    resources :projects
    resources :users
  end

  resources :projects, only: [:index, :show, :edit] do
    resources :categories do
      member do
        post 'move'
      end
      resources :features do
        member do
          post 'move'
        end
        resources :scenarios do
          member do
            post 'move'
          end
        end
      end
    end
  end

  resource :profile, only: [:show]


  get "dashboard/index"

  root to: 'dashboard#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :category_ids

  has_and_belongs_to_many :users
  has_many :categories

  validates :name, presence: true

  def display_name
    name
  end

  def root_categories
    categories.roots.all.sort_by!(&:position)
  end

end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < AdminController
    before_filter :load_project, only: [:show, :edit, :update, :destroy]

    def index
      @projects = Project.page(params[:page])
    end

    def show
      @project = Project.find params[:id]
    end

    def new
      @project = Project.new
    end

    def create
      @project = Project.new(params[:project])
      if @project.save
        redirect_to edit_admin_project_path(@project), notice: "Successfully created project."
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @project.update_attributes(params[:project])
        redirect_to edit_admin_project_path(@project), notice: "Successfully updated project."
      else
        render :edit
      end
    end

    def destroy
      redirect_to(admin_projects_path, alert: "project not found") and return if @project.nil?
      if @project.destroy
        redirect_to(admin_projects_path, notice: "Successfully deleted project")
      else
        redirect_to(admin_projects_path, alert: "project couldn't be deleted")
      end
    end


    private

    def load_project
      @project = Project.find params[:id]
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects.page(params[:page])
  end

  def show
    @project = current_user.projects.find(params[:id])
  end

  def edit
    @project = current_user.projects.find(params[:id])
    @current_category = params[:category_id]
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.haml
%li.span4[project]
  .thumbnail
    .caption
      %h3= project.name
      %p
        .progress
          .bar.bar-success{ style: "width: 35%;" }
          .bar.bar-warning{ style: "width: 20%;" }
          .bar.bar-danger{ style: "width: 10%;" }
      %p
        = link_to 'Open Project', project_path(project), class: 'btn btn-primary'

app/views/projects/edit.html.haml
.page-header

  .btn-toolbar.pull-right
    .btn-group
      = link_to new_project_category_path(@project), class: 'btn btn-success' do
        %i.icon-folder-close.icon-white
        New Category
    .btn-group
      = link_to project_path(@project), class: 'btn btn-primary' do
        %i.icon-search.icon-white
        Show Project

  = title(@project.display_name)


- unless @project.root_categories.blank?
  %ul.nav.nav-tabs.nav-stacked.sortable.accordion
    = render partial: 'categories/edit_category', collection: @project.root_categories, as: :category, locals: { current_category: @current_category }

app/views/projects/index.html.haml
.page-header

  -#.btn-group.pull-right
  -#  %a.btn.btn-primary{ href: new_project_path }
  -#    %i.icon-folder-close.icon-white
  -#    New Project

  = title('Projects')

%ul.thumbnails
  = render @projects
= paginate @projects

app/views/projects/show.html.haml
= content_for(:javascript) { render 'show.js' }

.page-header

  .btn-toolbar.pull-right
    .btn-group
      = link_to edit_project_path(@project), class: 'btn btn-primary' do
        %i.icon-edit.icon-white
        Edit Project

  = title(@project.display_name)

.btn-toolbar.pull-right

  .btn-group.resource-filter
    %button.btn.active{ name: 'everything' }
      %i.icon-folder-close
      %i.icon-file
      %i.icon-list
      Scenarios
    %button.btn{ name: 'features' }
      %i.icon-folder-close
      %i.icon-file
      Features
    %button.btn{ name: 'categories' }
      %i.icon-folder-close
      Categories

  .btn-group.content-filter
    %button.btn.active{ name: 'all' }
      %i.icon-plus
      %i.icon-plus
      %i.icon-plus
      Background
    %button.btn{ name: 'description' }
      %i.icon-plus
      %i.icon-plus
      Description
    %button.btn{ name: 'names' }
      %i.icon-plus
      Names

= render @project.root_categories