config/routes.rb
Sapm::Application.routes.draw do

  devise_for :users, controllers: { confirmations: "confirmations" }
  as :user do
    put '/users/confirmation' => 'confirmations#update', as: :update_user_confirmation
  end

  namespace :admin do
    resources :projects
    resources :users
  end

  resources :projects, only: [:index, :show, :edit] do
    resources :categories do
      member do
        post 'move'
      end
      resources :features do
        member do
          post 'move'
        end
        resources :scenarios do
          member do
            post 'move'
          end
        end
      end
    end
  end

  resource :profile, only: [:show]


  get "dashboard/index"

  root to: 'dashboard#index'
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  attr_accessible :description, :feature_id, :name, :position

  belongs_to :feature

  validates :name, presence: true
  validates :position, presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_create :set_position

  def display_name
    name
  end

  # ##
  # # Move the feature to a new position within the category.
  # def move_to_position(new_position)
  #   new_position ||= position
  #   new_position = new_position.to_i
  #   # TODO: Refactor - it shouldn't be necessary to make separate queries. Put up/down logic inside loop.
  #   moving_down = position < new_position
  #   if self.update_attribute(:position, new_position)
  #     Feature.transaction do
  #       last_occupied = -1
  #       operator = moving_down ? :<= : :<
  #       category.features.where("position #{operator} ?", position).order(:position).select { |f| f != self }.each do |ft|
  #         ft.update_attribute(:position, last_occupied + 1) if ft.position != last_occupied + 1
  #         last_occupied += 1
  #       end
  #       last_occupied = position
  #       operator = moving_down ? :> : :>=
  #       category.features.where("position #{operator} ?", position).order(:position).select { |f| f != self }.each do |ft|
  #         ft.update_attribute(:position, last_occupied + 1) if ft.position != last_occupied + 1
  #         last_occupied += 1
  #       end
  #     end
  #     true
  #   else
  #     false
  #   end
  # end

  private

  ##
  # Make sure that new scenarios are inserted last among their siblings.
  def set_position
    scenarios = feature.scenarios
    self.position = scenarios.blank? ? 0 : (scenarios.map(&:position).max + 1)
  end
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  before_filter :load_project
  before_filter :load_category
  before_filter :load_feature
  before_filter :load_scenario, only: [:show, :edit, :update, :destroy, :move]

  def show
  end

  def new
    @scenario = @feature.scenarios.new
  end

  def create
    @scenario = @feature.scenarios.new(params[:scenario].merge({ feature_id: @feature.id }))
    if @scenario.save
      redirect_to project_category_feature_path(@project, @category, @feature, scenario_id: @scenario.id), notice: "Successfully created scenario."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @scenario.update_attributes(params[:scenario].merge({ feature_id: @feature.id }))
      redirect_to project_category_feature_path(@project, @category, @feature, scenario_id: @scenario.id), notice: "Successfully updated scenario."
    else
      render :edit
    end
  end

  # def destroy
  #   redirect_to(project_category_feature_path(@project, @category, @feature), alert: "Scenario not found.") and return if @scenario.nil?
  #   if @scenario.destroy
  #     redirect_to(project_category_feature_path(@project, @category, @feature), notice: "Successfully deleted scenario.")
  #   else
  #     redirect_to(project_category_feature_path(@project, @category, @feature), alert: "Scenario couldn't be deleted.")
  #   end
  # end

  # ##
  # # Action called when a feature changes position (AJAX).
  # def move
  #   if @scenario.move_to_position(params[:position])
  #     render text: 'success'
  #   else
  #     render text: 'failure'
  #   end
  # end


  private

  def load_project
    @project = current_user.projects.find(params[:project_id])
  end

  def load_category
    @category = @project.categories.find(params[:category_id])
  end

  def load_feature
    @feature = @category.features.find(params[:feature_id])
  end

  def load_scenario
    @scenario = @feature.scenarios.find(params[:id])
  end

end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_edit_scenario.html.haml
- current_scenario ||= -1
- expanded = scenario.id == current_scenario.to_i

%li.ui-state-default[scenario]{ data: { expanded: expanded, url: move_project_category_feature_scenario_path(@project, @category, @feature, scenario) } }

  .btn.btn-link.handle.pull-right
    %i.icon-resize-vertical

  .btn-group.pull-right
    = link_to edit_project_category_feature_scenario_path(@project, @category, @feature, scenario), class: 'btn btn-small btn-warning' do
      %i.icon-edit.icon-white
      Edit
    = link_to(project_category_feature_scenario_path(@project, @category, @feature, scenario), method: :delete, confirm: 'Are you sure that you want to permanently delete this scenario?', class: 'btn btn-small btn-danger') do
      %i.icon-trash.icon-white
      Delete

  -#.scenarios.pull-right
  -#  %i.icon-list
  -#  %span.badge.badge-success= 0
  -#  \/
  -#  %span.badge= rand(10)+1

  = link_to '#', class: 'header' do
    = scenario.display_name


  .content
    - unless scenario.description.blank?
      .description
        %pre= scenario.description

app/views/scenarios/_form_inputs.html.haml
.form-inputs

  - unless f.object.feature.background.blank?
    .control-group
      %label.control-label.muted Background
      .controls
        .background
          %pre.muted= f.object.feature.background

  = f.input :name, as: :string, wrapper: :append do
    = f.input_field :name, autofocus: true, class: 'input-xxlarge'
    %span.add-on>
      %i.icon-list

  = f.input :description, as: :text, hint: "Given...<br/>When...<br/>Then...", input_html: { rows: 3, class: 'input-xxlarge' }

app/views/scenarios/_scenario.html.haml
.scenario[scenario]
  .title
    %h5
      %i.icon-list
      = scenario.display_name
  .body
    - unless scenario.description.blank?
      .description
        %pre= scenario.description

app/views/scenarios/edit.html.haml
.page-header
  = title(@scenario.display_name, @feature.display_name)

= simple_form_for(@scenario, url: project_category_feature_scenario_path(@project, @category, @feature, @scenario), html: { method: :put, class: 'form form-horizontal' }) do |f|
  = f.error_notification
  = render partial: 'form_inputs', locals: { f: f }
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to "Cancel", project_category_feature_path(@project, @category, @feature, scenario_id: @scenario.id), class: 'btn'

app/views/scenarios/new.html.haml
.page-header
  = title('New Scenario', "for the feature #{@feature.display_name}")

= simple_form_for(@scenario, url: project_category_feature_scenarios_path(@project, @category, @feature), html: { method: :post, class: 'form form-horizontal' }) do |f|
  = f.error_notification
  = render partial: 'form_inputs', locals: { f: f }
  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to "Cancel", project_category_feature_path(@project, @category, @feature), class: 'btn'