config/routes.rb
Sapm::Application.routes.draw do

  devise_for :users, controllers: { confirmations: "confirmations" }
  as :user do
    put '/users/confirmation' => 'confirmations#update', as: :update_user_confirmation
  end

  namespace :admin do
    resources :projects
    resources :users
  end

  resources :projects, only: [:index, :show, :edit] do
    resources :categories do
      member do
        post 'move'
      end
      resources :features do
        member do
          post 'move'
        end
        resources :scenarios do
          member do
            post 'move'
          end
        end
      end
    end
  end

  resource :profile, only: [:show]


  get "dashboard/index"

  root to: 'dashboard#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set

  attr_accessible :name, :parent_id, :position
  attr_protected :lft, :rgt, :depth

  belongs_to :project
  has_many :features
  has_many :scenarios, through: :features

  validates :name, presence: true
  validates :position, presence: true,
            numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  #validate :parent_valid

  before_create :set_position

  def ordered_children
    children.all.sort_by!(&:position)
  end

  def display_name
    name
  end

  def move_to_position(new_position)
    new_position ||= position
    new_position = new_position.to_i
    # TODO: Refactor - it shouldn't be necessary to make separate queries. Put up/down logic inside loop.
    moving_down = position < new_position
    if self.update_attribute(:position, new_position)
      Category.transaction do
        last_occupied = -1
        operator = moving_down ? :<= : :<
        siblings.where("position #{operator} ?", position).all.sort_by!(&:position).each do |cat|
          cat.update_attribute(:position, last_occupied + 1) if cat.position != last_occupied + 1
          last_occupied += 1
        end
        last_occupied = position
        operator = moving_down ? :> : :>=
        siblings.where("position #{operator} ?", position).all.sort_by!(&:position).each do |cat|
          cat.update_attribute(:position, last_occupied + 1) if cat.position != last_occupied + 1
          last_occupied += 1
        end
      end
      true
    else
      false
    end
  end

  private

  ##
  # We only allow a parent category that belongs to the same project.
  def parent_valid
    # TODO: Should we require the project to always be set for every category?
  end

  ##
  # Make sure that new categories are inserted last among their siblings.
  def set_position
    categories = project.nil? ? parent.children : project.categories
    self.position = categories.blank? ? 0 : (categories.map(&:position).max + 1)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :load_project
  before_filter :load_category, only: [:show, :edit, :update, :destroy, :move]

  def show
    @features = Feature.where(category_id: @category.self_and_descendants.map(&:id)).order(:position)
  end

  def new
    @category = @project.categories.new parent_id: params[:parent_id]
  end

  def create
    @category = @project.categories.new(params[:category].merge({ project_id: @project.id }))
    if @category.save
      redirect_to edit_project_path(@project, category_id: @category.id), notice: "Successfully created category."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(params[:category].merge({ project_id: @project.id }))
      redirect_to edit_project_path(@project, category_id: @category.id), notice: "Successfully updated category."
    else
      render :edit
    end
  end

  def destroy
    redirect_to(edit_project_path(@project), alert: "Category not found.") and return if @category.nil?
    if @category.destroy
      redirect_to(edit_project_path(@project), notice: "Successfully deleted category.")
    else
      redirect_to(edit_project_path(@project), alert: "Category couldn't be deleted.")
    end
  end

  ##
  # Action called when a category changes position (AJAX).
  def move
    if @category.move_to_position(params[:position])
      render text: 'success'
    else
      render text: 'failure'
    end
  end


  private

  def load_project
    @project = current_user.projects.find(params[:project_id])
  end

  def load_category
    @category = @project.categories.find(params[:id])
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
= leveled_block(category.level) do
  .category[category]
    .title
      = leveled_title(category.name, category.level + 2)
    .body
      .features
        -#.title
        -#  %h4 Features
        .body
          = render category.features.order(:position)
      .children= render category.ordered_children

app/views/categories/_edit_category.html.haml
- current_category ||= -1
- expanded = category.self_and_descendants.map(&:id).include?(current_category.to_i).to_s

%li.ui-state-default[category]{ data: { expanded: expanded, url: move_project_category_path(@project, category) } }

  .btn.btn-link.handle.pull-right
    %i.icon-resize-vertical

  .btn-group.pull-right
    = link_to new_project_category_path(@project, parent_id: category.id), class: 'btn btn-small btn-success' do
      %i.icon-folder-close.icon-white
      New

  .btn-group.pull-right
    = link_to project_category_path(@project, category), class: 'btn btn-small btn-primary' do
      %i.icon-search.icon-white
      Show
    = link_to edit_project_category_path(@project, category), class: 'btn btn-small btn-warning' do
      %i.icon-edit.icon-white
      Edit
    = link_to(project_category_path(@project, category), method: :delete, confirm: 'Are you sure that you want to permanently delete this category and any sub-categories?', class: 'btn btn-small btn-danger') do
      %i.icon-trash.icon-white
      Delete

  .categories.pull-right
    %i.icon-folder-close
    %span.badge.badge-success= 0
    \/
    %span.badge= category.descendants.count
    &nbsp;
    %i.icon-file
    %span.badge.badge-success= 0
    \/
    %span.badge= category.features.count
    &nbsp;
    %i.icon-list
    %span.badge.badge-success= 0
    \/
    %span.badge= category.scenarios.count

  = link_to project_category_path(@project, category), class: 'header' do
    = category.display_name


  .content
    - unless category.children.blank?
      %ul.nav.nav-tabs.nav-stacked.sortable.accordion
        = render partial: 'categories/edit_category', collection: category.ordered_children, as: :category, locals: { current_category: current_category }

app/views/categories/edit.html.haml
.page-header
  = title(@category.display_name, @project.display_name)

= simple_form_for(@category, url: project_category_path(@project, @category), html: { method: :put, class: 'form form-horizontal' }) do |f|

  = f.error_notification

  .form-inputs
    = f.input :name, as: :string, wrapper: :append do
      = f.input_field :name, autofocus: true
      %span.add-on>
        %i.icon-folder-close

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to "Cancel", edit_project_path(@project), class: 'btn'

app/views/categories/new.html.haml
.page-header
  = title('New Category', @project.display_name)

= simple_form_for(@category, url: project_categories_path(@project), html: { method: :post, class: 'form form-horizontal' }) do |f|

  = f.error_notification

  .form-inputs
    = f.input :name, as: :string, wrapper: :append do
      = f.input_field :name, autofocus: true
      %span.add-on>
        %i.icon-folder-close

  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    = link_to "Cancel", edit_project_path(@project), class: 'btn'

app/views/categories/show.html.haml
.page-header

  .btn-toolbar.pull-right
    .btn-group
      = link_to edit_project_path(@project), class: 'btn' do
        %i.icon-edit
        Edit Project
      = link_to edit_project_category_path(@project, @category), class: 'btn btn-primary' do
        %i.icon-edit.icon-white
        Edit Category
    .btn-group
      = link_to new_project_category_feature_path(@project, @category), class: 'btn btn-success' do
        %i.icon-file.icon-white
        New Feature

  = title(@category.display_name)

- unless @features.blank?
  %ul.nav.nav-tabs.nav-stacked.sortable.accordion
    = render partial: 'features/edit_feature', collection: @features, as: :feature