config/routes.rb
Sapm::Application.routes.draw do

  devise_for :users, controllers: { confirmations: "confirmations" }
  as :user do
    put '/users/confirmation' => 'confirmations#update', as: :update_user_confirmation
  end

  namespace :admin do
    resources :projects
    resources :users
  end

  resources :projects, only: [:index, :show, :edit] do
    resources :categories do
      member do
        post 'move'
      end
      resources :features do
        member do
          post 'move'
        end
        resources :scenarios do
          member do
            post 'move'
          end
        end
      end
    end
  end

  resource :profile, only: [:show]


  get "dashboard/index"

  root to: 'dashboard#index'
end

app/views/layouts/partials/_flash_messages.html.haml
- flash.each do |name, msg|
  - unless msg.blank?
    %div{ class: "alert alert-#{name == :notice ? "success" : "error"}" }
      %a.close{ data: { dismiss: "alert" } } &#215;
      = content_tag :div, msg, id: "flash_#{name}" if msg.is_a?(String)

app/views/layouts/partials/_footer.html.haml
.site-navigation
  .container-fluid
    .row
      .span3
        %h4 About
        %ul
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
      .span3
        %h4 Support
        %ul
          %li= link_to "Frequently Asked Questions", root_url
          %li= link_to "Ask a Question", root_url
          %li= link_to "Tutorials", root_url
          %li= link_to "Feedback", root_url
      .span3
        %h4 Legal
        %ul
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
      .span3
        %h4 Contact
        %ul
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url
          %li= link_to "About Us", root_url

.copyrights
  .container-fluid
    %small
      = raw "&copy; 2013-#{Date.today.year}"
      = link_to 'sapm.org', root_url

app/views/layouts/partials/_head.html.haml
%meta{ charset: "utf-8" }
%meta{ "http-equiv" => "X-UA-Compatible", content: "IE=edge,chrome=1" }
%meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1" }
%title= content_for?(:title) ? yield(:title) : "SAPM"
%meta{ content: "", :name => "description"}
%meta{ content: "Daniel Jonasson", name: "author"}
= stylesheet_link_tag "application", media: "all"
= yield :stylesheets
= csrf_meta_tags
= yield :head

app/views/layouts/partials/_header.html.haml
= render 'layouts/partials/navigation'

app/views/layouts/partials/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %a{ class: "btn btn-navbar", data: { toggle: "collapse", target: ".nav-collapse" } }
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.brand{ href: root_url  } SAPM

      - if user_signed_in?
        .btn-toolbar.pull-right
          - if current_user.administrator?
            .btn-group
              %a{ class: "btn dropdown-toggle", data: { toggle: "dropdown" }, href: "#" }
                %i.icon-cog
                Administration
                %span.caret
              %ul.dropdown-menu
                %li= link_to 'Manage Users', admin_users_path
                %li= link_to 'Manage Projects', admin_projects_path

          .btn-group
            %a.btn{ href: profile_path }
              %i.icon-user
              = current_user.display_name
            %a.btn.dropdown-toggle{ data: { toggle: "dropdown" }, href: "#" }
              %span.caret
            %ul.dropdown-menu
              %li= link_to('My Projects', projects_path)
              %li.divider
              %li= link_to('My Profile', profile_path)
              %li.divider
              %li= link_to('Sign out', :destroy_user_session, method: 'delete')


      - else
        .pull-right
          %ul.nav
            %li= link_to(t('.sign_in', default: 'Sign in'), :new_user_session)
            -#%li= link_to(t('.sign_up', default: 'Sign up'), '#') #TODO:new_user_registration_path)

      - if user_signed_in?
        .nav-collapse
          = render_navigation renderer: :bootstrap
          -#%ul.nav
          -#  %li= link_to 'Users', '#'
          -#  %li= link_to 'Projects', '#'

        -#%form.navbar-search.pull-left
        -#  %input{ type: "text", class: "search-query", placeholder: "Search"}